### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by lbgaus** [Vodurden/Http-Multipart-Data-Parser#13]
Hi Jake,

I am trying out your multipart parser, but am running into some issues with out of memory exceptions when constructing an instance. The file.bin file is 2.09 GB in size.

Here is my code, in VB:

Dim fileStream As New System.IO.FileStream("file.bin", IO.FileMode.Open, IO.FileAccess.Read)
Dim parser As New HttpMultipartParser.MultipartFormDataParser(fileStream, System.Text.Encoding.UTF8)

Running this code returns an OutOfMemoryException. Any ideas why this is? Thanks! :D

**Comment by Vodurden** [comment]
Hi lbgaus. I'm glad that the experimental feature has helped you! Today I've pushed version 1.1.0 of the parser which moves the ideas from the experimental branch into master. 

There is now a new class called StreamingMultipartDataParser which provides a similar interface to what we have discussed in this issue. If you find yourself parsing large multipart data again please use that instead of the experimental interface.

Thanks again for your collaboration on this issue. As 1.1.0 solves this problem I'm going to close this thread.
