### ISSUE TITLE
NET Core support

### ISSUE THREAD

**Issue by geoperez** [Vodurden/Http-Multipart-Data-Parser#44]
Hi, I found your project helpful but I can't use it directly from nuget because you don't support NET Core. My workaround was to copy your source code and it works fine with NET Core (only a little change with Serializable).

So I wonder if you will publish soon NET Core support.

Thank you

**Comment by ryanthompson0123** [comment]
+1 NET Core support would be great. Only alternative at this point is Microsoft.AspNet.WebApi.Client which isn't ideal (and isn't really NET Core either).

**Comment by Vodurden** [comment]
This seems like a good idea. I haven't been in the .NET world for a while so I'll need to spend a bit of time finding out what the best way to support both `.NET Framework` and `.NET Core` is but I'll take a look.

**Comment by geoperez** [comment]
You can target both in the same project, it's really easy.

**Comment by Vodurden** [comment]
So I've had a look around the documentation for .NET core and I can't form a clear picture of what would be required to correctly target both the existing `.NET Framework` and `.NET Core`. This is probably because I'm not active in the `.NET` community much anymore and as such I'm out of the loop.

I'm happy to accept a PR that converts the library to `.NET Core` support but it may take me a while to sort it out myself.

I'm also happy to accept any links/guides that might give me a better idea of what the project should look like in a `.NET Core` world.

**Comment by geoperez** [comment]
I had port some of my libraries to .NET Core, let me give it a try and post a PR.

**Comment by geoperez** [comment]
@Vodurden I just posted PR #45 with some notes.

**Comment by Vodurden** [comment]
Sorry for taking so long to deal with this issue and PR! Version 2.1.7 of this library just hit NuGet and *should* be .NET-Core compatible. Let me know if there are any issues.
