### ISSUE TITLE
"Object reference not set to an instance of an object" in GetParameterValue

### ISSUE THREAD

**Issue by Jericho** [Vodurden/Http-Multipart-Data-Parser#49]
The documentation for the `GetParameterValue` says: 
> Returns the value of a parameter or null if it doesn't exist.

However, if I try to get the value of a parameter that doesn't exist, I get a `Object reference not set to an instance of an object` exception.

This problem is caused by the following code in `MultipartFormDataParser.cs`:
```csharp
return Parameters.FirstOrDefault(p => p.Name == name).Data;
```

The issue is that `FirstOrDefault` returns a null value which cause the exception when trying to get the value in `.Data`.

I have a suggestion to resolve this issue and also to allow a default value to be specified when the parameter doesn't exist:
```csharp
public string GetParameterValue(string name, string defaultValue = null)
{
    if (parser.HasParameter(name)) return parser.GetParameterValue(name);
    else return defaultValue;
}
```

I would be happy to submit PR with this improvement

**Comment by Vodurden** [comment]
Hi Jericho, thanks for the feedback!

No need for a PR, I've resolved the issue here: https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/c3ea5e3e27e0e7204b1354aebc98a78093d1995e

I opted not to include the defaultValue feature as I find C#'s `??` to solve the default value case nicely: `GetParameterValue("mightExist") ?? "default"`

The change should be available in version 2.2.1 here: https://www.nuget.org/packages/HttpMultipartParser/2.2.1

I'm going to close this but feel free to comment if you continue to see the problem or have more feedback.

Thanks!

**Comment by Jericho** [comment]
Thanks for the quick fix. 

One thing I suggested and was hopping you would accept was the idea of being able to provided my own 'default value' instead of defaulting to 'null' when a parameter is missing.

**Comment by Vodurden** [comment]
Is there something that prevents you from using the C# `??` syntax? If
there is i could be persuaded to add a default but otherwise i world
recommend using `??` like so: `GetParameterValue (...) ?? "default"`

**Comment by Jericho** [comment]
It's true that I can use the `??` syntax, I just think it's more intuitive and elegant to offer the possibility of specifying the default value as a parameter. Additionally, this parameter is optional which means that it can be omitted.

Anyway, no big deal, I guess it's just my personal preference.
