### ISSUE TITLE
boundaryBinary issue

### ISSUE THREAD

**Issue by alrehamy** [Vodurden/Http-Multipart-Data-Parser#50]
##hello

in StreamingMultipartFormDataParser.cs file the method Run() recognizes the boundary by trying to find the matched bytes of "--" at the beginning and end of the file part ... what if by some mistake there is a false positive matching in the middle of the file's binary data, for instance, the post data contains a bate-encoded string "--" or even an HTML document (such as a web page http-posted from one server node to another for cache purpose)  that contains a comment like "!--"? in such cases boundary detection is invalid since only specific portion of the actual binary file data being serialized into "FilePart" type

**Comment by Vodurden** [comment]
Hi alrehamy,

The `DetectBoundary()` method looks first the _first_ match of `--` in the input binary. For us to match another `--` further in the file would mean that the multipart data would need to be uploaded with an invalid boundary which would make it invalid multipart regardless.

More specifically the multipart specification requires that data is uploaded in the form:

```
--randomlygeneratedboundary
...
--randomlygeneratedboundary
...
--randomlygeneratedboundary--
```

If for some reason we had:

```
--randomlygeneratedboundary
<!-- a html comment here -->
<p>Hello!</p>
--randomlygeneratedboundary--
```

Then the detection should work fine since we will match the first `--` and correctly detect `--randomlygeneratedboundary` as the boundary.

If for some reason we had:

```
<!-- a html comment here -->
<p>Hello!</p>
--randomlygeneratedboundary--
```

Then the detection will fail, but this is also an invalid multipart payload and we expect it should fail parsing.

If this still worries you the `StreamingMultipartFormDataParser` can be given a boundary as a parameter which will skip the detection algorithm.

Let me know if this explanation doesn't help. I'm also happy to be proven wrong so if you find a valid multipart upload that causes the detection to fail please add it to this thread and I'll check it out.
